### ISSUE TITLE
Cleaner metadata

### ISSUE THREAD

**Issue by ArchdukeTim** [wpilibsuite/OutlineViewer#19]
As of right now metadata has to be declared as `~METADATA~`. Is there a possibility of making it something easier, like starts with an underscore (or 2). This would also make it easy to quickly hide data, by just adding an underscore to the beginning, instead of changing the entire name.

**Comment by SamCarlberg** [comment]
This is something I've been thinking about. Leaning towards a dotfile-like naming scheme eg `.metadata`

**Comment by ArchdukeTim** [comment]
Although first outlineviewer has to actually detect and hide metadata when not requested
