### ISSUE TITLE
Keys should be editable

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/OutlineViewer#27]
Whenever I make a typo in a key field I need to delete the entry and then re-enter it again, hopefully with the correct name and the same value as before. It would be a lot nicer if I could edit the key in-place (which could be implemented as a delete and a put)

**Comment by ThadHouse** [comment]
We'd have to be careful that the key doesn't already exist in the table, and there is not really a good way to solve that race condition, but if that is something we can live with, that should be OK. I don't think implementing something like that at the ntcore level would be a good idea.

**Comment by SamCarlberg** [comment]
Doesn't ntcore already support that with force puts?

**Comment by ThadHouse** [comment]
Supports changing the type of a key. Not changing the name of a key. And I wouldn't want to override a key that already exists. Teams might end up getting very confused by that.
