### ISSUE TITLE
Proper metadata regex for JavaFX

### ISSUE THREAD

**Issue by ArchdukeTim** [wpilibsuite/OutlineViewer#40]
https://github.com/wpilibsuite/OutlineViewer/blob/JavaFX/src/main/java/edu/wpi/first/outlineviewer/model/Entry.java#L19

`^\..*$` should be the correct regex

**Comment by nightpool** [comment]
That would only match metadata in the root of the system. Furthermore, there's no reason to use a full capture. the correct regex is `/(.|~[^/]+~)`
