### ISSUE TITLE
Save & Load

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/OutlineViewer#41]
Add the ability to save and load a network tables state. Useful for debugging, could use JSON or XML or something.

@bradamiller

**Comment by SamCarlberg** [comment]
How is this different from the current record/playback functionality in shuffleboard?

**Comment by AustinShalit** [comment]
This would let you save a single state of NetworkTables.  Looks like this is going to be implemented at the ntcore level.

**Comment by bradamiller** [comment]
The idea is just to be able to load different test data sets for playing with shuffleboard. Rather than having to write a program to generate the values that are then recorded. And using record/playback if you want to add a few additional keys, then you’d have to re-record.
