### ISSUE TITLE
Arrays are not editable

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/OutlineViewer#64]
Adding and editing values in an array, followed by clicking "Add", does not result in the array being updated.  Double arrays are not editable at all.

**Comment by AustinShalit** [comment]
So what is going on here is the commit event is not being fired because it can only be fired right now by pressing return in the text field.  Looking into a fix.

**Comment by bradamiller** [comment]
Can you do a losing focus event to trigger it?

**Comment by AustinShalit** [comment]
That is what I am thinking.

**Comment by barhenkro** [comment]
Is there any way to edit a number array?
I tried to edit  a number array and it didn't work but I succeeded to edit string arrays and boolean arrays

**Comment by brhea** [comment]
I just ran into this issue also... trying to edit a double array and it doesn't work. It's important to be able to write to double arrays.

I tried editing a string array and it worked fine.

It appears that this issue has been open for some time.
