### ISSUE TITLE
Add option for command line arguments. 

### ISSUE THREAD

**Issue by alamo3** [wpilibsuite/OutlineViewer#84]
Hello,
I'm trying to write a vision application and would greatly appreciate if we could get the ability to start the outline viewer and set the preferences through launching it through cmd.

**Comment by AustinShalit** [comment]
What preferences do you want on the command line?

**Comment by alamo3** [comment]
The ability to start as server or client mode along with the team number and port would be great if it can be added.

**Comment by team4015** [comment]
The goal would be to go past the initial dialogue straight to the outline viewer itself as the preferences for start have already been selected through command line arguments
