### ISSUE TITLE
GUI not loading properly after launching once

### ISSUE THREAD

**Issue by r4stered** [wpilibsuite/OutlineViewer#92]
Hey, 

I'm on Arch Linux with KDE and have run into an issue where Outline Viewer will start up and let people connect the first time, however if I quit the program and relaunch the program, it only comes up with small window with nothing in it. It will not work until I restart my computer and then it repeats the same behaviour. 

![image](https://user-images.githubusercontent.com/6174102/62342672-b7f6dd00-b4b5-11e9-8b46-c8dcf202f4ca.png)

Java Version:
```
➜  OutlineViewer git:(master) java --version 
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11)
OpenJDK 64-Bit Server VM (build 11.0.4+11, mixed mode)
```

I only have pynetworktables installed and nothing else on the system. Maybe it's an issue on my end?

Thanks!

**Comment by Mee42** [comment]
Will it have anything on the window if you expand it to a reasonable size?

**Comment by r4stered** [comment]
@Mee42 It doesn't let me expand the window at all. It's like nothing is actually getting rendered.

**Comment by PeterJohnson** [comment]
I’m seeing the same thing on Ubuntu with KDE.  Not sure if KDE is related to issue.

**Comment by r4stered** [comment]
@PeterJohnson I would suspect so. I can check on another DE with the same computer soon.

**Comment by AustinShalit** [comment]
What happens if you change the gtk version to 3?

https://github.com/wpilibsuite/OutlineViewer/blob/d82acb21b1b912bdfd293ad1f4be5f8c26537fbf/src/main/java/edu/wpi/first/outlineviewer/Main.java#L15-L17

**Comment by PeterJohnson** [comment]
No change in behavior

**Comment by r4stered** [comment]
Thanks for the quick fix! Really appreciate it
